# Generated by Django 3.0.3 on 2020-03-18 10:52

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='time duration is in minutes')),
                ('total_ques', models.IntegerField()),
                ('forum', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_score', to='events.Event')),
                # ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='registration.player')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'verbose_name_plural': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('html', tinymce.models.HTMLField(null=True)),
                ('correct_score', models.IntegerField()),
                ('answer', fernet_fields.fields.EncryptedTextField()),
                ('incorrect_score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.Event')),
            ],
            options={
                'verbose_name_plural': 'questions',
            },
        ),
        # migrations.AddField(
        #     model_name='event',
        #     name='player_score',
        #     field=models.ManyToManyField(related_name='event_num', through='events.Score', to='registration.player'),
        # ),
        # migrations.AddField(
        #     model_name='event',
        #     name='society',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.society'),
        # ),
    ]
