# Generated by Django 3.0.3 on 2020-03-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='societyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.society'),
        ),
        migrations.AddField(
            model_name='answers',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Question'),
        ),
    ]
