# Generated by Django 3.0.3 on 2020-03-08 07:29

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_societyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
