# Generated by Django 3.0.3 on 2020-03-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200303_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='userId',
            new_name='user',
        ),
    ]
