# Generated by Django 3.0.3 on 2020-03-08 08:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200308_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='html',
            field=tinymce.models.HTMLField(),
        ),
    ]
