# Generated by Django 3.0.3 on 2020-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_event',
            field=models.ManyToManyField(related_name='player_info', through='events.Score', to='events.Event'),
        ),
    ]
